# istio-installation.yaml
apiVersion: istio.openshift.com/v1alpha3
kind: ControlPlane
metadata:
  name: basic-install
spec:
  launcher:
    enabled: false
    # specify the url to master, e.g. https://master.some.domain.com:443
    LAUNCHER_MISSIONCONTROL_OPENSHIFT_CONSOLE_URL:
    # Your GitHub username ()
    LAUNCHER_MISSIONCONTROL_GITHUB_USERNAME:
    # Your GitHub Mission Control access token
    LAUNCHER_MISSIONCONTROL_GITHUB_TOKEN:

  threeScale:
    enabled: false

  istio:
    global:
      proxy:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 128Mi

    gateways:
      istio-egressgateway:
        autoscaleEnabled: true
        autoscaleMax: 3
      istio-ingressgateway:
        autoscaleEnabled: true
        autoscaleMax: 3
        ior_enabled: true

    mixer:
      policy:
        autoscaleEnabled: true
        autoscaleMax: 3

      telemetry:
        autoscaleEnabled: false
        resources:
          requests:
            cpu: 100m
            memory: 1G
          limits:
            cpu: 500m
            memory: 4G

    pilot:
      autoscaleEnabled: false
      traceSampling: 100.0

    kiali:
      dashboard:
        user: admin
        passphrase: admin
    tracing:
      enabled: true
